# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: test
        run: |
          cp -f ./actiontmate.sh actiontmate.sh
          mkdir -p ~/work/lede/lede/
          cp actiontmate.sh ~/work/lede/lede/.config
          cd ~/work/lede/lede/
          ls -a
